import { NextRequest, NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

interface MutualFund {
  schemeName: string
  schemeCode: string
  category: string
  returns_1y: string
  returns_3y: string
  returns_5y: string
  expense_ratio: string
  aum: string
  rating: number
  fund_house: string
  risk_level: string
  min_investment: string
}

// Curated representative funds with realistic ranges (educational display data).
const FUNDS_BY_CATEGORY: Record<string, MutualFund[]> = {
  equity: [
    {
      schemeName: 'SBI Blue Chip Fund - Direct Plan - Growth',
      schemeCode: '120503',
      category: 'Large Cap',
      returns_1y: '15.2%',
      returns_3y: '18.5%',
      returns_5y: '16.8%',
      expense_ratio: '0.63%',
      aum: '₹25,000 Cr',
      rating: 4.5,
      fund_house: 'SBI Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹500',
    },
    {
      schemeName: 'Mirae Asset Large Cap Fund - Direct - Growth',
      schemeCode: '118551',
      category: 'Large Cap',
      returns_1y: '18.1%',
      returns_3y: '19.8%',
      returns_5y: '17.2%',
      expense_ratio: '0.52%',
      aum: '₹21,500 Cr',
      rating: 4.8,
      fund_house: 'Mirae Asset',
      risk_level: 'Moderate',
      min_investment: '₹500',
    },
    {
      schemeName: 'Parag Parikh Flexi Cap Fund - Direct - Growth',
      schemeCode: '122639',
      category: 'Flexi Cap',
      returns_1y: '22.4%',
      returns_3y: '21.3%',
      returns_5y: '19.6%',
      expense_ratio: '0.59%',
      aum: '₹48,000 Cr',
      rating: 4.9,
      fund_house: 'PPFAS Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹1000',
    },
    {
      schemeName: 'UTI Nifty 50 Index Fund - Direct - Growth',
      schemeCode: '120682',
      category: 'Index',
      returns_1y: '14.8%',
      returns_3y: '15.9%',
      returns_5y: '14.7%',
      expense_ratio: '0.22%',
      aum: '₹9,800 Cr',
      rating: 4.4,
      fund_house: 'UTI Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹500',
    },
  ],
  debt: [
    {
      schemeName: 'HDFC Corporate Bond Fund - Direct - Growth',
      schemeCode: '119598',
      category: 'Corporate Bond',
      returns_1y: '7.6%',
      returns_3y: '7.1%',
      returns_5y: '7.8%',
      expense_ratio: '0.44%',
      aum: '₹31,000 Cr',
      rating: 4.5,
      fund_house: 'HDFC Mutual Fund',
      risk_level: 'Low',
      min_investment: '₹100',
    },
    {
      schemeName: 'ICICI Pru Short Term Fund - Direct - Growth',
      schemeCode: '120757',
      category: 'Short Duration',
      returns_1y: '7.2%',
      returns_3y: '6.8%',
      returns_5y: '7.1%',
      expense_ratio: '0.48%',
      aum: '₹18,500 Cr',
      rating: 4.3,
      fund_house: 'ICICI Prudential',
      risk_level: 'Low',
      min_investment: '₹100',
    },
    {
      schemeName: 'SBI Magnum Gilt Fund - Direct - Growth',
      schemeCode: '119692',
      category: 'Gilt',
      returns_1y: '8.9%',
      returns_3y: '6.4%',
      returns_5y: '8.2%',
      expense_ratio: '0.55%',
      aum: '₹12,200 Cr',
      rating: 4.1,
      fund_house: 'SBI Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹500',
    },
  ],
  hybrid: [
    {
      schemeName: 'HDFC Balanced Advantage Fund - Direct - Growth',
      schemeCode: '118908',
      category: 'Balanced Advantage',
      returns_1y: '16.5%',
      returns_3y: '14.2%',
      returns_5y: '13.8%',
      expense_ratio: '0.67%',
      aum: '₹72,000 Cr',
      rating: 4.6,
      fund_house: 'HDFC Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹100',
    },
    {
      schemeName: 'ICICI Pru Equity & Debt Fund - Direct - Growth',
      schemeCode: '119940',
      category: 'Aggressive Hybrid',
      returns_1y: '17.8%',
      returns_3y: '16.5%',
      returns_5y: '15.9%',
      expense_ratio: '0.70%',
      aum: '₹41,000 Cr',
      rating: 4.4,
      fund_house: 'ICICI Prudential',
      risk_level: 'Moderate',
      min_investment: '₹100',
    },
    {
      schemeName: 'SBI Conservative Hybrid Fund - Direct - Growth',
      schemeCode: '119512',
      category: 'Conservative Hybrid',
      returns_1y: '9.2%',
      returns_3y: '8.6%',
      returns_5y: '8.9%',
      expense_ratio: '0.58%',
      aum: '₹15,400 Cr',
      rating: 4.2,
      fund_house: 'SBI Mutual Fund',
      risk_level: 'Low',
      min_investment: '₹500',
    },
  ],
  elss: [
    {
      schemeName: 'Quant ELSS Tax Saver Fund - Direct - Growth',
      schemeCode: '120640',
      category: 'ELSS',
      returns_1y: '28.3%',
      returns_3y: '27.1%',
      returns_5y: '22.4%',
      expense_ratio: '0.72%',
      aum: '₹19,800 Cr',
      rating: 4.7,
      fund_house: 'Quant Mutual Fund',
      risk_level: 'High',
      min_investment: '₹500',
    },
    {
      schemeName: 'Mirae Asset Tax Saver Fund - Direct - Growth',
      schemeCode: '120543',
      category: 'ELSS',
      returns_1y: '19.4%',
      returns_3y: '20.1%',
      returns_5y: '17.5%',
      expense_ratio: '0.55%',
      aum: '₹22,000 Cr',
      rating: 4.6,
      fund_house: 'Mirae Asset',
      risk_level: 'High',
      min_investment: '₹500',
    },
    {
      schemeName: 'SBI Long Term Equity Fund - Direct - Growth',
      schemeCode: '119598',
      category: 'ELSS',
      returns_1y: '16.7%',
      returns_3y: '17.9%',
      returns_5y: '16.1%',
      expense_ratio: '0.61%',
      aum: '₹24,600 Cr',
      rating: 4.3,
      fund_house: 'SBI Mutual Fund',
      risk_level: 'High',
      min_investment: '₹500',
    },
  ],
  gold: [
    {
      schemeName: 'SBI Gold Fund - Direct - Growth',
      schemeCode: '120689',
      category: 'Gold FoF',
      returns_1y: '19.8%',
      returns_3y: '13.2%',
      returns_5y: '12.6%',
      expense_ratio: '0.48%',
      aum: '₹11,200 Cr',
      rating: 4.3,
      fund_house: 'SBI Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹100',
    },
    {
      schemeName: 'HDFC Gold Fund - Direct - Growth',
      schemeCode: '121632',
      category: 'Gold FoF',
      returns_1y: '19.6%',
      returns_3y: '13.0%',
      returns_5y: '12.4%',
      expense_ratio: '0.52%',
      aum: '₹8,700 Cr',
      rating: 4.2,
      fund_house: 'HDFC Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹100',
    },
  ],
  international: [
    {
      schemeName: 'Motilal Oswal Nasdaq 100 Fund of Fund - Direct - Growth',
      schemeCode: '122473',
      category: 'International',
      returns_1y: '24.1%',
      returns_3y: '17.8%',
      returns_5y: '19.2%',
      expense_ratio: '0.85%',
      aum: '₹14,900 Cr',
      rating: 4.6,
      fund_house: 'Motilal Oswal',
      risk_level: 'High',
      min_investment: '₹500',
    },
    {
      schemeName: 'Franklin India Feeder - Franklin US Opportunities - Direct - Growth',
      schemeCode: '122345',
      category: 'International',
      returns_1y: '18.9%',
      returns_3y: '15.4%',
      returns_5y: '16.8%',
      expense_ratio: '0.94%',
      aum: '₹7,300 Cr',
      rating: 4.4,
      fund_house: 'Franklin Templeton',
      risk_level: 'High',
      min_investment: '₹500',
    },
  ],
  smallcap: [
    {
      schemeName: 'Nippon India Small Cap Fund - Direct - Growth',
      schemeCode: '119985',
      category: 'Small Cap',
      returns_1y: '26.7%',
      returns_3y: '28.4%',
      returns_5y: '25.1%',
      expense_ratio: '0.68%',
      aum: '₹37,500 Cr',
      rating: 4.7,
      fund_house: 'Nippon India',
      risk_level: 'Very High',
      min_investment: '₹100',
    },
    {
      schemeName: 'SBI Small Cap Fund - Direct - Growth',
      schemeCode: '120606',
      category: 'Small Cap',
      returns_1y: '24.9%',
      returns_3y: '26.8%',
      returns_5y: '23.7%',
      expense_ratio: '0.62%',
      aum: '₹29,400 Cr',
      rating: 4.6,
      fund_house: 'SBI Mutual Fund',
      risk_level: 'Very High',
      min_investment: '₹500',
    },
  ],
  index: [
    {
      schemeName: 'UTI Nifty 50 Index Fund - Direct - Growth',
      schemeCode: '120682',
      category: 'Index',
      returns_1y: '14.8%',
      returns_3y: '15.9%',
      returns_5y: '14.7%',
      expense_ratio: '0.22%',
      aum: '₹9,800 Cr',
      rating: 4.4,
      fund_house: 'UTI Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹500',
    },
    {
      schemeName: 'HDFC Index Fund - Nifty 50 Plan - Direct - Growth',
      schemeCode: '121573',
      category: 'Index',
      returns_1y: '14.6%',
      returns_3y: '15.7%',
      returns_5y: '14.5%',
      expense_ratio: '0.20%',
      aum: '₹6,900 Cr',
      rating: 4.3,
      fund_house: 'HDFC Mutual Fund',
      risk_level: 'Moderate',
      min_investment: '₹100',
    },
  ],
}

const DEFAULT_CATEGORY = 'equity'

export async function GET(request: NextRequest, { params }: { params: { category: string } }) {
  const category = params?.category?.toLowerCase() || DEFAULT_CATEGORY
  const funds = FUNDS_BY_CATEGORY[category] || FUNDS_BY_CATEGORY[DEFAULT_CATEGORY]

  return NextResponse.json({
    category,
    top_performers: funds,
    note: 'Representative educational data based on public fund information. Not investment advice.',
  })
}